#ifndef TCPSEARCHPLUGIN_GLOBAL_H
#define TCPSEARCHPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TCPSEARCHPLUGIN_LIBRARY)
#  define TCPSEARCHPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define TCPSEARCHPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // TCPSEARCHPLUGIN_GLOBAL_H
